-- CREATE TABLE users (
--     id VARCHAR(255) NOT NULL,
--     firstName VARCHAR(50) NOT NULL,
--     lastName VARCHAR(50) NOT NULL,
--     email VARCHAR(150) NOT NULL,
--     hash VARCHAR(255) NOT NULL,
--     isEmployee tinyint,
--     isManager tinyint,
--     PRIMARY KEY (id),
--     UNIQUE KEY email (email)
-- );

-- ALTER TABLE users ALTER isEmployee SET DEFAULT 0;
-- ALTER TABLE users ALTER isManager SET DEFAULT 0;

-- CREATE TABLE businesses (
--     id VARCHAR(255) NOT NULL,
--     name VARCHAR(50) NOT NULL,
--     lat FLOAT(11, 7) NOT NULL,
--     lng FLOAT(11, 7) NOT NULL,
--     PRIMARY KEY (id)
-- );

-- ALTER TABLE businesses ADD COLUMN pin VARCHAR(50) AFTER lng;
-- ALTER TABLE businesses ADD UNIQUE KEY (pin);
-- ALTER TABLE businesses ADD COLUMN managerId VARCHAR(255) AFTER id;
-- DROP TABLE businessManagers;

-- CREATE TABLE businessEmployees (
--     id int NOT NULL AUTO_INCREMENT,
--     employeeId VARCHAR(255) NOT NULL,
--     businessId VARCHAR(255) NOT NULL,
--     PRIMARY KEY (id),
--     INDEX employeesAndBusinesses (employeeId, businessId),
--     FOREIGN KEY (employeeId) 
--         REFERENCES users(id)
--         ON DELETE CASCADE,
--     FOREIGN KEY (businessId) 
--         REFERENCES businesses(id)
--         ON DELETE CASCADE
-- );

-- CREATE TABLE businessManagers (
--     id int NOT NULL AUTO_INCREMENT,
--     managerId VARCHAR(255) NOT NULL,
--     businessId VARCHAR(255) NOT NULL,
--     PRIMARY KEY (id),
--     INDEX managersAndBusinesses (managerId, businessId),
--     FOREIGN KEY (managerId) 
--         REFERENCES users(id)
--         ON DELETE CASCADE,
--     FOREIGN KEY (businessId) 
--         REFERENCES businesses(id)
--         ON DELETE CASCADE
-- );

-- CREATE TABLE employeeTimes (
--     id int NOT NULL AUTO_INCREMENT,
--     employeeId VARCHAR(255) NOT NULL,
--     businessId VARCHAR(255) NOT NULL,
--     clockIn BIGINT(20) NOT NULL,
--     clockOut BIGINT(20),
--     PRIMARY KEY (id),
--     INDEX employeesAndBusinesses (employeeId, businessId),
--     FOREIGN KEY (employeeId) 
--         REFERENCES users(id)
--         ON DELETE CASCADE,
--     FOREIGN KEY (businessId) 
--         REFERENCES businesses(id)
--         ON DELETE CASCADE
-- );

-- ALTER TABLE employeeTimes ADD COLUMN isPaid tinyint AFTER clockOut;
-- ALTER TABLE employeeTimes ALTER isPaid SET DEFAULT 0;